"""Add uniqe constrain in quizattempt

Revision ID: 12452c35ece6
Revises: 33c8823f4f4e
Create Date: 2025-09-10 01:26:46.115146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12452c35ece6'
down_revision: Union[str, Sequence[str], None] = '33c8823f4f4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizattempt', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_active_attempt', ['quiz_id', 'user_id', 'submitted_at'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizattempt', schema=None) as batch_op:
        batch_op.drop_constraint('uq_active_attempt', type_='unique')

    # ### end Alembic commands ###
