"""Add a new column in quizattempt shuffle_data

Revision ID: 668e72a5571a
Revises: 0e3d8ba85814
Create Date: 2025-09-14 16:32:15.207073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '668e72a5571a'
down_revision: Union[str, Sequence[str], None] = '0e3d8ba85814'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizattempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shuffle_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizattempt', schema=None) as batch_op:
        batch_op.drop_column('shuffle_data')

    # ### end Alembic commands ###
