"""Fix all cascade deletes and FKs

Revision ID: 78f0bc4e10e0
Revises: dc349f4878ac
Create Date: 2025-09-06 23:45:29.251275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f0bc4e10e0'
down_revision: Union[str, Sequence[str], None] = 'dc349f4878ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('option_question_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('quiz_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('question_quiz_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'quiz', ['quiz_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('quizanswer', schema=None) as batch_op:
        batch_op.alter_column('attempt_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('quizanswer_selected_option_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('quizanswer_question_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('quizanswer_attempt_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'quizattempt', ['attempt_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'option', ['selected_option_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('quizresult', schema=None) as batch_op:
        batch_op.alter_column('attempt_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('quizresult_attempt_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'quizattempt', ['attempt_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizresult', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('quizresult_attempt_id_fkey'), 'quizattempt', ['attempt_id'], ['id'])
        batch_op.alter_column('attempt_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('quizanswer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('quizanswer_attempt_id_fkey'), 'quizattempt', ['attempt_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('quizanswer_question_id_fkey'), 'question', ['question_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('quizanswer_selected_option_id_fkey'), 'option', ['selected_option_id'], ['id'])
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('attempt_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('question_quiz_id_fkey'), 'quiz', ['quiz_id'], ['id'])
        batch_op.alter_column('quiz_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('option', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('option_question_id_fkey'), 'question', ['question_id'], ['id'])
        batch_op.alter_column('question_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
