"""update uniqe constrain in quizattempt with attempt number 

Revision ID: b703c8283483
Revises: 12452c35ece6
Create Date: 2025-09-10 12:12:06.253672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b703c8283483'
down_revision: Union[str, Sequence[str], None] = '12452c35ece6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizattempt', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_active_attempt'), type_='unique')
        batch_op.create_unique_constraint('uq_attempt_number', ['quiz_id', 'user_id', 'attempt_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizattempt', schema=None) as batch_op:
        batch_op.drop_constraint('uq_attempt_number', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_active_attempt'), ['quiz_id', 'user_id', 'submitted_at'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
