"""Fix cascade deletes for QuizAttempt

Revision ID: dc349f4878ac
Revises: b42bcb4c22cb
Create Date: 2025-09-06 23:39:12.795414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc349f4878ac'
down_revision: Union[str, Sequence[str], None] = 'b42bcb4c22cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizattempt', schema=None) as batch_op:
        batch_op.alter_column('quiz_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('quizattempt_quiz_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('quizattempt_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'quiz', ['quiz_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizattempt', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('quizattempt_user_id_fkey'), 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('quizattempt_quiz_id_fkey'), 'quiz', ['quiz_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quiz_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
